# Generated by Django 2.2.3 on 2019-07-17 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titres', '0001_initial'),
        ('Compte_Epargne_Action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotitle',
            name='user_name',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolioTitle', to='Compte_Epargne_Action.PortfolioTitle'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_name',
            field=models.ForeignKey(db_column='company_name', on_delete=django.db.models.deletion.CASCADE, to='titres.CompanyDetail'),
        ),
    ]
