# Generated by Django 2.2.3 on 2019-07-17 13:22

from django.db import migrations, models
import titres.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('company_name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('company_web', models.CharField(max_length=200)),
                ('company_fullname', models.CharField(max_length=25, unique=True)),
                ('company_photo', models.ImageField(blank=True, upload_to='uploads')),
                ('company_phone', models.IntegerField(default=None)),
                ('company_address', models.CharField(max_length=200)),
                ('company_descp', models.TextField()),
                ('company_industry', models.CharField(max_length=120)),
                ('company_date_launch', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50, validators=[titres.models.validate_even])),
                ('date_value', models.DateField()),
                ('current_value', models.FloatField()),
                ('origin_value', models.FloatField()),
                ('high_value', models.FloatField()),
                ('low_value', models.FloatField()),
                ('opening_value', models.FloatField()),
                ('closing_value', models.FloatField()),
                ('devise_value', models.CharField(max_length=3)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('quantity_title', models.IntegerField()),
                ('company_name', models.ForeignKey(db_column='company_fullname', default=None, on_delete=False, to='titres.CompanyDetail', to_field='company_fullname')),
            ],
        ),
    ]
